exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /www/dev/vendor/houdunwang/db/src/connection/Connection.php:49
Stack trace:
#0 /www/dev/vendor/houdunwang/db/src/connection/Connection.php(49): PDO->__construct('mysql:host=loca...', 'root', 'admin888', Array)
#1 /www/dev/vendor/houdunwang/db/src/connection/Connection.php(30): houdunwang\db\connection\Mysql->link()
#2 /www/dev/vendor/houdunwang/db/src/Query.php(63): houdunwang\db\connection\Mysql->__construct(Object(houdunwang\db\Query))
#3 /www/dev/vendor/houdunwang/db/src/Query.php(52): houdunwang\db\Query->connection()
#4 /www/dev/vendor/houdunwang/db/src/Db.php(26): houdunwang\db\Query->config(Array)
#5 /www/dev/vendor/houdunwang/db/src/Db.php(33): houdunwang\db\Db->driver()
#6 [internal function]: houdunwang\db\Db->__call('query', Array)
#7 [internal function]: houdunwang\db\Db->query('SHOW TABLES')
#8 /www/dev/vendor/houdunwang/db/src/Db.php(40): call_user_func_array(Array, Array)
#9 /www/dev/vendor/houdunwang/database/src/build/Mysql.php(209): houdunwang\db\Db::__callStatic('query', Array)
#10 /www/dev/vendor/houdunwang/database/src/build/Mysql.php(209): houdunwang\db\Db::query('SHOW TABLES')
#11 [internal function]: houdunwang\database\build\Mysql->tableExists('migrations')
#12 /www/dev/vendor/houdunwang/database/src/build/Base.php(51): call_user_func_array(Array, Array)
#13 [internal function]: houdunwang\database\build\Base->__call('tableExists', Array)
#14 [internal function]: houdunwang\database\build\Base->tableExists('migrations')
#15 /www/dev/vendor/houdunwang/database/src/Schema.php(35): call_user_func_array(Array, Array)
#16 [internal function]: houdunwang\database\Schema->__call('tableExists', Array)
#17 [internal function]: houdunwang\database\Schema->tableExists('migrations')
#18 /www/dev/vendor/houdunwang/framework/src/build/Facade.php(42): call_user_func_array(Array, Array)
#19 /www/dev/vendor/houdunwang/cli/src/build/migrate/Migrate.php(18): houdunwang\framework\build\Facade::__callStatic('tableExists', Array)
#20 /www/dev/vendor/houdunwang/cli/src/build/migrate/Migrate.php(18): houdunwang\database\SchemaFacade::tableExists('migrations')
#21 /www/dev/vendor/houdunwang/cli/src/build/Base.php(41): houdunwang\cli\build\migrate\Migrate->__construct()
#22 [internal function]: houdunwang\cli\build\Base->bootstrap()
#23 /www/dev/vendor/houdunwang/cli/src/Cli.php(24): call_user_func_array(Array, Array)
#24 [internal function]: houdunwang\cli\Cli->__call('bootstrap', Array)
#25 [internal function]: houdunwang\cli\Cli->bootstrap()
#26 /www/dev/vendor/houdunwang/cli/src/Cli.php(37): call_user_func_array(Array, Array)
#27 /www/dev/vendor/houdunwang/framework/src/build/Base.php(52): houdunwang\cli\Cli::__callStatic('bootstrap', Array)
#28 /www/dev/vendor/houdunwang/framework/src/build/Base.php(52): houdunwang\cli\Cli::bootstrap()
#29 [internal function]: houdunwang\framework\build\Base->bootstrap()
#30 /www/dev/vendor/houdunwang/framework/src/App.php(27): call_user_func_array(Array, Array)
#31 [internal function]: houdunwang\framework\App->__call('bootstrap', Array)
#32 [internal function]: houdunwang\framework\App->bootstrap()
#33 /www/dev/vendor/houdunwang/framework/src/App.php(41): call_user_func_array(Array, Array)
#34 /www/dev/system/hdphp.php(19): houdunwang\framework\App::__callStatic('bootstrap', Array)
#35 /www/dev/system/hdphp.php(19): houdunwang\framework\App::bootstrap()
#36 /www/dev/hd(2): require('/www/dev/system...')
#37 {main}